
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA ID INS LLAVEA LLAVEC NOTA PAREA PAREC PIPE PLAY TIEMPO\n\tnuestroCompilador : expression\n\t\t\t\t\t  | empty\n\t\n\texpression : ID PAREA INS COMA TIEMPO PAREC LLAVEA notas LLAVEC\n\t\n\texpression : expression expression\n\t\n\tnotas : NOTA\n\t\n\tnotas : NOTA COMA notas\n\t\n\texpression : PLAY PAREA r PAREC\n\t\n\tr : ID\n\t\n\tr : ID COMA r\n\t\n\tr : PAREA o PAREC\n\t\n\to : ID\n\t\n\to : ID PIPE o\n\t\n\tempty :\n\t'
    
_lr_action_items = {'ID':([0,2,6,8,10,16,17,20,27,],[4,4,4,12,15,-7,12,15,-3,]),'PLAY':([0,2,6,16,27,],[5,5,5,-7,-3,]),'$end':([0,1,2,3,6,16,27,],[-13,0,-1,-2,-4,-7,-3,]),'PAREA':([4,5,8,17,],[7,8,10,10,]),'INS':([7,],[9,]),'COMA':([9,12,26,],[13,17,28,]),'PAREC':([11,12,14,15,18,19,21,23,],[16,-8,19,-11,22,-10,-9,-12,]),'TIEMPO':([13,],[18,]),'PIPE':([15,],[20,]),'LLAVEA':([22,],[24,]),'NOTA':([24,28,],[26,26,]),'LLAVEC':([25,26,29,],[27,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'nuestroCompilador':([0,],[1,]),'expression':([0,2,6,],[2,6,6,]),'empty':([0,],[3,]),'r':([8,17,],[11,21,]),'o':([10,20,],[14,23,]),'notas':([24,28,],[25,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> nuestroCompilador","S'",1,None,None,None),
  ('nuestroCompilador -> expression','nuestroCompilador',1,'p_InterpreteMusical','nuestroCompilador.py',88),
  ('nuestroCompilador -> empty','nuestroCompilador',1,'p_InterpreteMusical','nuestroCompilador.py',89),
  ('expression -> ID PAREA INS COMA TIEMPO PAREC LLAVEA notas LLAVEC','expression',9,'p_expression_function','nuestroCompilador.py',96),
  ('expression -> expression expression','expression',2,'p_expression_empty','nuestroCompilador.py',108),
  ('notas -> NOTA','notas',1,'p_notas','nuestroCompilador.py',115),
  ('notas -> NOTA COMA notas','notas',3,'p_notas_many','nuestroCompilador.py',122),
  ('expression -> PLAY PAREA r PAREC','expression',4,'p_expression_play','nuestroCompilador.py',129),
  ('r -> ID','r',1,'p_r','nuestroCompilador.py',136),
  ('r -> ID COMA r','r',3,'p_r_many','nuestroCompilador.py',147),
  ('r -> PAREA o PAREC','r',3,'p_r_parallel','nuestroCompilador.py',158),
  ('o -> ID','o',1,'p_o','nuestroCompilador.py',165),
  ('o -> ID PIPE o','o',3,'p_o_many','nuestroCompilador.py',175),
  ('empty -> <empty>','empty',0,'p_empty','nuestroCompilador.py',185),
]
